openapi: 3.0.3
info:
  title: Brain Rot Chronicles - Logging Service
  description: >
    Service centralisé de gestion des logs. 
    Ingestion asynchrone via RabbitMQ et stockage NoSQL.
    Standardise les traces de tous les microservices pour le monitoring et l'audit.
  version: 1.0.0
servers:
  - url: http://localhost:4010/api/v1/logs
    description: Serveur de développement local

paths:
  /:
    get:
      summary: Consultation globale des logs
      description: Permet de filtrer l'activité système. Réservé aux administrateurs (isSigma).
      tags: [Consultation]
      security:
        - bearerAuth: []
      parameters:
        - name: limit
          in: query
          schema: { type: integer, default: 50 }
        - name: offset
          in: query
          schema: { type: integer, default: 0 }
        - name: serviceSource
          in: query
          description: "Nom du service émetteur (ex: auth-service)."
          schema: { type: string }
        - name: level
          in: query
          description: Sévérité du log.
          schema: { type: string, enum: [INFO, WARN, ERROR, DEBUG] }
        - name: userId
          in: query
          description: Filtrer par l'identifiant d'un utilisateur.
          schema: { type: string, format: uuid }
        - name: traceId
          in: query
          description: ID unique de transaction pour suivre une requête.
          schema: { type: string }
      responses:
        '200':
          description: Liste des logs récupérée avec pagination.
          content:
            application/json:
              schema:
                type: object
                required: [items, total]
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/LogEntry'
                  total:
                    type: integer
                    example: 125
        '400':
          description: Paramètres invalides.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '500':
          $ref: '#/components/responses/InternalError'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    LogEntry:
      type: object
      required: [timestamp, service, level, message, traceId]
      properties:
        service:
          type: string
          description: Nom du service émetteur.
          example: "auth-service"
        level:
          type: string
          enum: [INFO, WARN, ERROR, FATAL]
          example: "INFO"
        message:
          type: string
          description: Message descriptif.
          example: "Utilisateur connecté avec succès."
        timestamp:
          type: string
          format: date-time
          example: "2026-02-02T14:00:00Z"
        payload:
          type: object
          additionalProperties: true
          description: Données contextuelles flexibles (userId, action, input, etc.).
          example: { "userId": "uuid-1234", "ip": "127.0.0.1" }
        traceId:
          type: string
          description: ID de corrélation pour le traçage distribué.
          example: "abc-123-xyz"

    ErrorModel:
      type: object
      required: [code, message]
      properties:
        code: { type: string, example: "LOG_NOT_FOUND" }
        message: { type: string, example: "Aucun log correspondant trouvé." }
        timestamp: { type: string, format: date-time }

  responses:
    UnauthorizedError:
      description: Authentification JWT échouée.
      content:
        application/json:
          schema: { $ref: '#/components/schemas/ErrorModel' }
    ForbiddenError:
      description: Accès refusé (isSigma requis).
      content:
        application/json:
          schema: { $ref: '#/components/schemas/ErrorModel' }
    NotFoundError:
      description: Ressource introuvable.
      content:
        application/json:
          schema: { $ref: '#/components/schemas/ErrorModel' }
    InternalError:
      description: Erreur serveur inattendue.
      content:
        application/json:
          schema: { $ref: '#/components/schemas/ErrorModel' }